/// JavaScript charting test
Class IBW.Chart Extends %ZEN.application
{

/// This is the name of this application.
Parameter APPLICATIONNAME = "Chart";

/// This is the URL of the main starting page of this application.
Parameter HOMEPAGE = "IBW.ChartHome.cls";

/// This Style block contains application-wide CSS style definitions.
XData Style
{
<style type="text/css">
</style>
}

}
